# Generated by Django 2.2.2 on 2019-06-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190624_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_id',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
